"""upgrade_class_model_to_enterprise

Revision ID: 27b2d48294a8
Revises: 592ca182bb29
Create Date: 2026-02-26 06:54:11.222011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b2d48294a8'
down_revision: Union[str, Sequence[str], None] = '592ca182bb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_instructor_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'instructor_id', name='unique_instructor_per_class')
    )
    op.create_index(op.f('ix_class_instructor_maps_class_id'), 'class_instructor_maps', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_instructor_maps_id'), 'class_instructor_maps', ['id'], unique=False)
    op.create_index(op.f('ix_class_instructor_maps_institution_id'), 'class_instructor_maps', ['institution_id'], unique=False)
    op.create_index(op.f('ix_class_instructor_maps_instructor_id'), 'class_instructor_maps', ['instructor_id'], unique=False)
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_column('students', 'class_id')
    op.drop_index(op.f('ix_class_instructor_maps_instructor_id'), table_name='class_instructor_maps')
    op.drop_index(op.f('ix_class_instructor_maps_institution_id'), table_name='class_instructor_maps')
    op.drop_index(op.f('ix_class_instructor_maps_id'), table_name='class_instructor_maps')
    op.drop_index(op.f('ix_class_instructor_maps_class_id'), table_name='class_instructor_maps')
    op.drop_table('class_instructor_maps')
    # ### end Alembic commands ###
