"""Add SchoolClass model

Revision ID: 592ca182bb29
Revises: d1045d67f05f
Create Date: 2026-02-22 16:54:57.513540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592ca182bb29'
down_revision: Union[str, Sequence[str], None] = 'd1045d67f05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('class_label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'academic_year_id', 'grade', 'section', name='unique_class_per_year')
    )
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index('ix_classes_institution_academic_year', 'classes', ['institution_id', 'academic_year_id'], unique=False)
    op.create_index(op.f('ix_classes_institution_id'), 'classes', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_institution_id'), table_name='classes')
    op.drop_index('ix_classes_institution_academic_year', table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
