"""enterprise_integrity_refactor

Revision ID: feac28fedeae
Revises: 3192b99bea98
Create Date: 2026-02-19 20:24:45.428138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feac28fedeae'
down_revision: Union[str, Sequence[str], None] = '3192b99bea98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attendance_student_date', 'attendance', ['student_id', 'date'], unique=False)
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('action_type', sa.String(), nullable=False))
    op.add_column('institutions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('institutions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_institutions_is_active'), 'institutions', ['is_active'], unique=False)
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_students_institution', 'students', ['institution_id'], unique=False)
    op.create_index(op.f('ix_students_is_active'), 'students', ['is_active'], unique=False)
    op.create_index('ix_survey_student_month', 'survey_responses', ['student_id', 'month', 'year'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_users_institution_role', 'users', ['institution_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('ix_users_institution_role', table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_active')
    op.drop_index('ix_survey_student_month', table_name='survey_responses')
    op.drop_index(op.f('ix_students_is_active'), table_name='students')
    op.drop_index('ix_students_institution', table_name='students')
    op.drop_column('students', 'deleted_at')
    op.drop_column('students', 'is_active')
    op.drop_index(op.f('ix_institutions_is_active'), table_name='institutions')
    op.drop_column('institutions', 'deleted_at')
    op.drop_column('institutions', 'is_active')
    op.drop_column('audit_logs', 'action_type')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_index('ix_attendance_student_date', table_name='attendance')
    # ### end Alembic commands ###
